services:
  mkdocs:
    image: harbor.alpha-quant.com.cn:5000/3rd_party/docker.io/squidfunk/mkdocs-material:9.5.33
    network_mode: "host"
    # ports:
    #   - "8005:8000"
    volumes:
      - ./libs/blog.liaosirui.com:/docs
      - ./site:/site
      - ./.icons:/.icons
      - ./mkdocs.yml:/mkdocs.yml
    stdin_open: true
    tty: true
    working_dir: /
    entrypoint: ["/usr/local/bin/mkdocs"]
    # command: ["serve", "--dev-addr=0.0.0.0:8000", "--no-livereload"]
    command: ["build"]
    init: true
